// packages/svelte/src/lib/Base.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { IconProps } from "./types";
  import { getIconContext } from "./context";

  interface BaseProps extends IconProps {
    icons: Map<string, string>;
    children?: Snippet;
  }

  const { alt, color, size, mirrored, mono, icons, children, ...rest }: BaseProps = $props();

  const context = getIconContext();

  const resolvedColor = $derived(color ?? context.color ?? "currentColor");
  const resolvedSize = $derived(size ?? context.size ?? "1em");
  const resolvedMirrored = $derived(mirrored ?? context.mirrored ?? false);
  const resolvedMono = $derived(mono ?? context.mono ?? false);
  const iconContent = $derived(icons.get(resolvedMono ? "font" : "icon") ?? "");
</script>

<svg
  xmlns="http://www.w3.org/2000/svg"
  width={resolvedSize}
  height={resolvedSize}
  fill={resolvedColor}
  viewBox="0 0 600 600"
  transform={resolvedMirrored ? "scale(-1, 1)" : undefined}
  {...rest}
>
  {#if alt}<title>{alt}</title>{/if}
  {#if children}{@render children()}{/if}
  {@html iconContent}
</svg>

// packages/react/src/lib/base.tsx
import React, { forwardRef, useContext, ReactElement } from 'react';
import { IconContext } from './ctx';
import { IconProps, IconType } from './types';

interface BaseProps extends IconProps {
  icons: Map<IconType, ReactElement>;
}

const Base = forwardRef<SVGSVGElement, BaseProps>((props, ref) => {
  const { color, size, mirrored, children, icons, ...rest } = props;

  const {
    alt,
    color: contextColor = 'currentColor',
    size: contextSize,
    mirrored: contextMirrored = false,
    mono: contextMono = false,
    ...restContext
  } = useContext(IconContext);

  return (
    <svg
      ref={ref}
      xmlns="http://www.w3.org/2000/svg"
      width={size ?? contextSize}
      height={size ?? contextSize}
      fill={color ?? contextColor}
      viewBox="0 0 600 600"
      transform={mirrored || contextMirrored ? 'scale(-1, 1)' : undefined}
      {...restContext}
      {...rest}>
      {!!alt && <title>{alt}</title>}
      {children}
      {icons.get(contextMono ? "font" : "icon")}
    </svg>
  );
});

Base.displayName = 'Base';

export default Base;
